'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "src@/components/Header/Header";
import Footer from "src@/components/Footer/Footer";
import { ThemeProvider } from "styled-components";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// className={`${geistSans.variable} ${geistMono.variable}`}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={{}}>
        <body style= {{display: "flex", flexDirection: "column", minHeight: "100vh"}}>
          <Header />
          <main style={{flex: "1"}}>
            {children}
          </main>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
